# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ORGANISER:     ROLE_USER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
          main:
              pattern: ^/
              ajax_form_login:
                  check_path: /login_check
                  login_path: /login
                  provider: fos_userbundle
                  always_use_default_target_path: true
              logout:
                  path:    /logout
                  success_handler: redirect.after.logout
                 # provider: fos_userbundle
                 # csrf_provider: form.csrf_provider

              anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }