# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: TournamentBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    redirect.after.logout:
        class: UserBundle\Redirection\AfterLogoutRedirection
        arguments: ["@router"]